### ISSUE TITLE
Handle cases when input is given without using autocomplete

### ISSUE THREAD

**Issue by MarkKoz** [Zer0897/code-jam-5#4]
The current implementation relies on autocomplete to provide coordinates. A user can type something without using autocomplete, but a search in such case would currently result in a 400.

One solution is to fall back to using the given name to search for a city when coordinates are not present. Another is to possibly force the top result in autocomplete to be picked, but this may end up making the wrong choice.

**Comment by intendednull** [comment]
Forcing the autocomplete would be cleaner. The top choice should be good enough since the edge cases are (probably) few and far between.
